
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.plaf.basic.BasicScrollBarUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kate
 */
public class MyContactsForm extends javax.swing.JFrame {

    /**
     * Creates new form MyContactsForm
     */
    public static int currentsUserId;
    
    public MyContactsForm() {
        initComponents();
        populateJtable();
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.white);
        jTable1.setBackground(Color.white);
        JTableHeader th = jTable1.getTableHeader();
        th.setForeground(Color.black);
        th.setBackground(Color.white);
        
        th.setFont(new Font("Tahoma", Font.PLAIN, 12));
        Contacts.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        jPanelGroups = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelContacts = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelRequest = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();
        Contacts = new javax.swing.JPanel();
        jPanelMainContacts = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jButtonAddContact1 = new javax.swing.JButton();
        jButtonEditContact = new javax.swing.JButton();
        jButtonDeleteContact = new javax.swing.JButton();
        jTextFieldId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldLname = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFname = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelClose2 = new javax.swing.JLabel();
        Groups = new javax.swing.JPanel();
        jPanelMainContacts1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButtonSendGroup = new javax.swing.JButton();
        jButtonDeleteGroup = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jButtonCreatGroup1 = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jTextFieldGroupsName = new javax.swing.JTextField();
        jTextFieldGroupsSend = new javax.swing.JTextField();
        jTextFieldGroupsId = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jButtonEditGroup1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableGroups = new javax.swing.JTable();
        jLabelClose1 = new javax.swing.JLabel();
        Request = new javax.swing.JPanel();
        jPanelMainContacts3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButtonRequestAdd = new javax.swing.JButton();
        jButtonRequestRefuse = new javax.swing.JButton();
        jTextRequestUserId = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldRequestLname = new javax.swing.JTextField();
        jTextFieldRequestFname = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldFname1 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldRequestUname = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jTextRequestId1 = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextRequestGroupID = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        jLabelClose3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRequest = new javax.swing.JTable();
        jLabelClose = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUserName.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabelUserName.setText("Username");
        getContentPane().add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(167, 65, 74));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelGroups.setBackground(new java.awt.Color(196, 91, 98));
        jPanelGroups.setToolTipText("");
        jPanelGroups.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGroupsMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contact_manager/contact_manager_img/Group_32px.png"))); // NOI18N
        jLabel8.setText("       Groups");

        javax.swing.GroupLayout jPanelGroupsLayout = new javax.swing.GroupLayout(jPanelGroups);
        jPanelGroups.setLayout(jPanelGroupsLayout);
        jPanelGroupsLayout.setHorizontalGroup(
            jPanelGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGroupsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        jPanelGroupsLayout.setVerticalGroup(
            jPanelGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sidepane.add(jPanelGroups, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 50));

        jPanelContacts.setBackground(new java.awt.Color(226, 117, 123));
        jPanelContacts.setToolTipText("");
        jPanelContacts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelContactsMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contact_manager/contact_manager_img/Contact_32px.png"))); // NOI18N
        jLabel9.setText("       Contacts");

        javax.swing.GroupLayout jPanelContactsLayout = new javax.swing.GroupLayout(jPanelContacts);
        jPanelContacts.setLayout(jPanelContactsLayout);
        jPanelContactsLayout.setHorizontalGroup(
            jPanelContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        jPanelContactsLayout.setVerticalGroup(
            jPanelContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sidepane.add(jPanelContacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, 50));

        jPanelRequest.setBackground(new java.awt.Color(196, 91, 98));
        jPanelRequest.setToolTipText("");
        jPanelRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRequestMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contact_manager/contact_manager_img/Invite_32px.png"))); // NOI18N
        jLabel10.setText("       Request");

        javax.swing.GroupLayout jPanelRequestLayout = new javax.swing.GroupLayout(jPanelRequest);
        jPanelRequest.setLayout(jPanelRequestLayout);
        jPanelRequestLayout.setHorizontalGroup(
            jPanelRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRequestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        jPanelRequestLayout.setVerticalGroup(
            jPanelRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sidepane.add(jPanelRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, 50));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 650));

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setLayout(new java.awt.CardLayout());

        Contacts.setBackground(new java.awt.Color(255, 255, 255));
        Contacts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMainContacts.setBackground(new java.awt.Color(102, 102, 102));
        jPanelMainContacts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanelMainContacts.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jTextFieldAddress.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldAddress.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldAddress.setBorder(null);
        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });
        jPanelMainContacts.add(jTextFieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 190, 30));

        jButtonAddContact1.setBackground(new java.awt.Color(0, 102, 0));
        jButtonAddContact1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddContact1.setText("Add");
        jButtonAddContact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddContact1ActionPerformed(evt);
            }
        });
        jPanelMainContacts.add(jButtonAddContact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, 30));

        jButtonEditContact.setBackground(new java.awt.Color(0, 102, 0));
        jButtonEditContact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditContact.setText("Edit");
        jButtonEditContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditContactActionPerformed(evt);
            }
        });
        jPanelMainContacts.add(jButtonEditContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 110, 30));

        jButtonDeleteContact.setBackground(new java.awt.Color(0, 102, 0));
        jButtonDeleteContact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeleteContact.setText("Delete");
        jButtonDeleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteContactActionPerformed(evt);
            }
        });
        jPanelMainContacts.add(jButtonDeleteContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 110, 30));

        jTextFieldId.setEditable(false);
        jTextFieldId.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldId.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldId.setBorder(null);
        jPanelMainContacts.add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last Name:");
        jPanelMainContacts.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jTextFieldLname.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldLname.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldLname.setBorder(null);
        jPanelMainContacts.add(jTextFieldLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 190, 30));

        jTextFieldPhone.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldPhone.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPhone.setBorder(null);
        jPanelMainContacts.add(jTextFieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 190, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone:");
        jPanelMainContacts.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address:");
        jPanelMainContacts.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");
        jPanelMainContacts.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jTextFieldFname.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldFname.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldFname.setBorder(null);
        jPanelMainContacts.add(jTextFieldFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 190, 30));
        jPanelMainContacts.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 190, 20));
        jPanelMainContacts.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 190, 20));
        jPanelMainContacts.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, 20));
        jPanelMainContacts.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 190, 20));
        jPanelMainContacts.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 190, 20));

        Contacts.add(jPanelMainContacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 690, 290));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Contacts.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 690, 320));

        jLabelClose2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelClose2.setForeground(new java.awt.Color(167, 65, 74));
        jLabelClose2.setText("X");
        jLabelClose2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose2MouseClicked(evt);
            }
        });
        Contacts.add(jLabelClose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 30, 40));

        Content.add(Contacts, "card3");

        Groups.setBackground(new java.awt.Color(255, 255, 255));
        Groups.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMainContacts1.setBackground(new java.awt.Color(102, 102, 102));
        jPanelMainContacts1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID");
        jPanelMainContacts1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jButtonSendGroup.setBackground(new java.awt.Color(0, 102, 0));
        jButtonSendGroup.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSendGroup.setText("Send Request");
        jButtonSendGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSendGroupMouseClicked(evt);
            }
        });
        jButtonSendGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendGroupActionPerformed(evt);
            }
        });
        jPanelMainContacts1.add(jButtonSendGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 140, 30));

        jButtonDeleteGroup.setBackground(new java.awt.Color(0, 102, 0));
        jButtonDeleteGroup.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeleteGroup.setText("Delete");
        jButtonDeleteGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteGroupMouseClicked(evt);
            }
        });
        jButtonDeleteGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteGroupActionPerformed(evt);
            }
        });
        jPanelMainContacts1.add(jButtonDeleteGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 90, 30));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Group Name");
        jPanelMainContacts1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelMainContacts1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 190, 240));
        jPanelMainContacts1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 190, 20));

        jButtonCreatGroup1.setBackground(new java.awt.Color(0, 102, 0));
        jButtonCreatGroup1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCreatGroup1.setText("Add");
        jButtonCreatGroup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCreatGroup1MouseClicked(evt);
            }
        });
        jButtonCreatGroup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreatGroup1ActionPerformed(evt);
            }
        });
        jPanelMainContacts1.add(jButtonCreatGroup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 90, 30));
        jPanelMainContacts1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 190, 10));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Group Name");
        jPanelMainContacts1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
        jPanelMainContacts1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 190, 0));

        jTextFieldGroupsName.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldGroupsName.setBorder(null);
        jPanelMainContacts1.add(jTextFieldGroupsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 190, 30));

        jTextFieldGroupsSend.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldGroupsSend.setBorder(null);
        jPanelMainContacts1.add(jTextFieldGroupsSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 190, 30));

        jTextFieldGroupsId.setEditable(false);
        jTextFieldGroupsId.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldGroupsId.setBorder(null);
        jPanelMainContacts1.add(jTextFieldGroupsId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 190, 30));
        jPanelMainContacts1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 190, 10));

        jButtonEditGroup1.setBackground(new java.awt.Color(0, 102, 0));
        jButtonEditGroup1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditGroup1.setText("Edit");
        jButtonEditGroup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditGroup1MouseClicked(evt);
            }
        });
        jButtonEditGroup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditGroup1ActionPerformed(evt);
            }
        });
        jPanelMainContacts1.add(jButtonEditGroup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 90, 30));

        Groups.add(jPanelMainContacts1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 690, 260));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTableGroups.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTableGroups.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableGroups.setGridColor(new java.awt.Color(255, 255, 255));
        jTableGroups.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGroupsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableGroups);

        Groups.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 690, 400));

        jLabelClose1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelClose1.setForeground(new java.awt.Color(167, 65, 74));
        jLabelClose1.setText("X");
        jLabelClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose1MouseClicked(evt);
            }
        });
        Groups.add(jLabelClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 30, 40));

        Content.add(Groups, "card2");

        Request.setBackground(new java.awt.Color(255, 255, 255));
        Request.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMainContacts3.setBackground(new java.awt.Color(102, 102, 102));
        jPanelMainContacts3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID");
        jPanelMainContacts3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jButtonRequestAdd.setBackground(new java.awt.Color(0, 102, 0));
        jButtonRequestAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRequestAdd.setText("Add");
        jButtonRequestAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRequestAddMouseClicked(evt);
            }
        });
        jButtonRequestAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRequestAddActionPerformed(evt);
            }
        });
        jPanelMainContacts3.add(jButtonRequestAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 110, 30));

        jButtonRequestRefuse.setBackground(new java.awt.Color(0, 102, 0));
        jButtonRequestRefuse.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRequestRefuse.setText("refuse");
        jButtonRequestRefuse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRequestRefuseMouseClicked(evt);
            }
        });
        jButtonRequestRefuse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRequestRefuseActionPerformed(evt);
            }
        });
        jPanelMainContacts3.add(jButtonRequestRefuse, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 110, 30));

        jTextRequestUserId.setEditable(false);
        jTextRequestUserId.setBackground(new java.awt.Color(102, 102, 102));
        jTextRequestUserId.setForeground(new java.awt.Color(255, 255, 255));
        jTextRequestUserId.setBorder(null);
        jTextRequestUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRequestUserIdActionPerformed(evt);
            }
        });
        jPanelMainContacts3.add(jTextRequestUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 190, 30));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("User Name:");
        jPanelMainContacts3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jTextFieldRequestLname.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldRequestLname.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldRequestLname.setBorder(null);
        jPanelMainContacts3.add(jTextFieldRequestLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 190, 30));

        jTextFieldRequestFname.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldRequestFname.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldRequestFname.setBorder(null);
        jPanelMainContacts3.add(jTextFieldRequestFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 190, 30));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("User ID");
        jPanelMainContacts3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jTextFieldFname1.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldFname1.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldFname1.setBorder(null);
        jPanelMainContacts3.add(jTextFieldFname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 190, 30));
        jPanelMainContacts3.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 190, 20));
        jPanelMainContacts3.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 190, 20));
        jPanelMainContacts3.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 190, 20));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Last Name:");
        jPanelMainContacts3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jTextFieldRequestUname.setBackground(new java.awt.Color(102, 102, 102));
        jTextFieldRequestUname.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldRequestUname.setBorder(null);
        jPanelMainContacts3.add(jTextFieldRequestUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 190, 30));
        jPanelMainContacts3.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 190, 20));

        jTextRequestId1.setEditable(false);
        jTextRequestId1.setBackground(new java.awt.Color(102, 102, 102));
        jTextRequestId1.setForeground(new java.awt.Color(255, 255, 255));
        jTextRequestId1.setBorder(null);
        jPanelMainContacts3.add(jTextRequestId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 190, 30));
        jPanelMainContacts3.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 190, 20));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("First Name");
        jPanelMainContacts3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Group ID");
        jPanelMainContacts3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        jTextRequestGroupID.setEditable(false);
        jTextRequestGroupID.setBackground(new java.awt.Color(102, 102, 102));
        jTextRequestGroupID.setForeground(new java.awt.Color(255, 255, 255));
        jTextRequestGroupID.setBorder(null);
        jTextRequestGroupID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRequestGroupIDActionPerformed(evt);
            }
        });
        jPanelMainContacts3.add(jTextRequestGroupID, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 190, 30));
        jPanelMainContacts3.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 190, 20));

        Request.add(jPanelMainContacts3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 690, 290));

        jLabelClose3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelClose3.setForeground(new java.awt.Color(167, 65, 74));
        jLabelClose3.setText("X");
        jLabelClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose3MouseClicked(evt);
            }
        });
        Request.add(jLabelClose3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 30, 40));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTableRequest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTableRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableRequest.setGridColor(new java.awt.Color(255, 255, 255));
        jTableRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRequestMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableRequest);

        Request.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 690, 220));

        jLabelClose.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(167, 65, 74));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        Request.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 30, 40));

        Content.add(Request, "card2");

        bg.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 690, 650));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 960, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void populateJtable(){
        contactQuery cq = new contactQuery();
        ArrayList<contact> ctList = cq.contactList(currentsUserId);
        String[] colNames = {"Id","First Name", "Last Name","Phone","Address"};
        Object[][] rows = new Object[ctList.size()][5];
        
        for(int i=0; i<ctList.size(); i++){
            rows[i][0] = ctList.get(i).getCid();
            rows[i][1] = ctList.get(i).getFname();
            rows[i][2] = ctList.get(i).getLname();
            rows[i][3] = ctList.get(i).getPhone();
            rows[i][4] = ctList.get(i).getAddress();
            
            
        }
        MyModel mmd = new MyModel(rows,colNames);
        jTable1.setModel(mmd);
        jTable1.setRowHeight(40);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(150);
    }
    public void populateGroupJtable() throws SQLException{
        groupQuery gq = new groupQuery();
        ArrayList<group> gtList = gq.groupList(currentsUserId);
        String[] colNames = {"Id","Group Name"};
        Object[][] rows = new Object[gtList.size()][2];
        
        for(int i=0; i<gtList.size(); i++){
            rows[i][0] = gtList.get(i).getGid();
            rows[i][1] = gtList.get(i).getGname();
            
            
        }
        MyModel mmd = new MyModel(rows,colNames);
        jTableGroups.setModel(mmd);
        jTableGroups.setRowHeight(40);
        jTableGroups.getColumnModel().getColumn(1).setPreferredWidth(150);
    }
 
    public void populateRequestJtable() throws SQLException{
        userQuery uq = new userQuery();
        ArrayList<user> usList = uq.memberList(currentsUserId);
        String[] colNames = {"id","User id","First Name","Last Name","User Name","Group ID"};
        Object[][] rows = new Object[usList.size()][6];
        
        for(int i=0; i<usList.size(); i++){
            rows[i][0] = usList.get(i).getId();
            rows[i][1] = usList.get(i).getUid();
            rows[i][2] = usList.get(i).getFname();
            rows[i][3] = usList.get(i).getLname();
            rows[i][4] = usList.get(i).getUname();
            rows[i][4] = usList.get(i).getGroupID();
            
            
            
        }
        MyModel mmd = new MyModel(rows,colNames);
        jTableRequest.setModel(mmd);
        jTableRequest.setRowHeight(40);
        jTableRequest.getColumnModel().getColumn(5).setPreferredWidth(150);
    }
    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jButtonDeleteContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteContactActionPerformed
        
        if(!jTextFieldId.getText().equals("")){
            int id = Integer.valueOf(jTextFieldId.getText());
            contactQuery cq = new contactQuery();
            cq.deleteContact(id);
            refreshJtable();
            clearFields();
        }else{
            JOptionPane.showMessageDialog(null, "Select A Contact From Table");
        }
        
        
  

    }//GEN-LAST:event_jButtonDeleteContactActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        //display selected JTable row data
        
        
        //get selected row index`
        int rowIndex = jTable1.getSelectedRow();
        jTextFieldFname.setText(jTable1.getValueAt(rowIndex,1).toString());
        jTextFieldLname.setText(jTable1.getValueAt(rowIndex,2).toString());
        
        
     
        jTextFieldAddress.setText(jTable1.getValueAt(rowIndex,4).toString());
        jTextFieldId.setText(jTable1.getValueAt(rowIndex,0).toString());
        jTextFieldPhone.setText(jTable1.getValueAt(rowIndex,3).toString());
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonAddContact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddContact1ActionPerformed
        
        String fname = jTextFieldFname.getText();
        String lname = jTextFieldLname.getText();
        String phone = jTextFieldPhone.getText();
        String Address = jTextFieldAddress.getText();
        System.out.println("bla:"+fname);
        if(fname.isEmpty() || lname.isEmpty() || phone.isEmpty() || Address.isEmpty() ){
            JOptionPane.showMessageDialog(null, "You Must Fill All Fields");
        }else{     
        contact c = new contact(null,fname,lname,Address,phone,currentsUserId);
        contactQuery cq = new contactQuery();
        cq.insertContact(c);
        refreshJtable();
        clearFields();
        }
    }//GEN-LAST:event_jButtonAddContact1ActionPerformed

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed

    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    public void refreshJtable(){
        jTable1.setModel(new DefaultTableModel());
        jTableGroups.setModel(new DefaultTableModel());
        populateJtable();
        try {
            populateGroupJtable();
            populateRequestJtable();
            
        } catch (SQLException ex) {
            Logger.getLogger(MyContactsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void clearFields()
    {
        jTextFieldId.setText("");
        jTextFieldFname.setText("");
        jTextFieldLname.setText("");
        jTextFieldPhone.setText("");
        jTextFieldAddress.setText("");
        jTextFieldGroupsId.setText("");
        jTextFieldGroupsName.setText("");
        jTextFieldGroupsSend.setText("");
        
        
    }
    private void jButtonEditContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditContactActionPerformed
        if(!jTextFieldId.getText().equals("")){
            int id = Integer.valueOf(jTextFieldId.getText());
            String fname = jTextFieldFname.getText();
            String lname = jTextFieldLname.getText();
            String phone = jTextFieldPhone.getText();
            String Address = jTextFieldAddress.getText();
           

            contact c = new contact(id,fname,lname,Address,phone,currentsUserId);
            contactQuery cq = new contactQuery();
            cq.updateContact(c);
            refreshJtable();
        }else{
            JOptionPane.showMessageDialog(null, "Select A Contact From Table");
        }
        
    }//GEN-LAST:event_jButtonEditContactActionPerformed

    private void jPanelContactsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelContactsMouseClicked
        setPanelColor(jPanelContacts);
        resetPanelColor(jPanelGroups);
        resetPanelColor(jPanelRequest);
        Contacts.setVisible(true);
        Groups.setVisible(false);
        Request.setVisible(false);
        
    }//GEN-LAST:event_jPanelContactsMouseClicked

    private void jPanelGroupsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGroupsMouseClicked
        try {
            setPanelColor(jPanelGroups);
            resetPanelColor(jPanelContacts);
            resetPanelColor(jPanelRequest);
            Contacts.setVisible(false);
            Groups.setVisible(true);
            Request.setVisible(false);
      
            populateGroupJtable();
            jTableGroups.setShowGrid(true);
            jTableGroups.setGridColor(Color.white);
            jTableGroups.setBackground(Color.white);
            JTableHeader th = jTable1.getTableHeader();
            th.setForeground(Color.black);
            th.setBackground(Color.white);
        
        th.setFont(new Font("Tahoma", Font.PLAIN, 12));
        } catch (SQLException ex) {
            Logger.getLogger(MyContactsForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jPanelGroupsMouseClicked

    private void jPanelRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRequestMouseClicked
        try {
            setPanelColor(jPanelRequest);
            resetPanelColor(jPanelContacts);
            resetPanelColor(jPanelGroups);
            populateRequestJtable();
            jTableGroups.setShowGrid(true);
            jTableGroups.setGridColor(Color.white);
            jTableGroups.setBackground(Color.white);
            JTableHeader th = jTable1.getTableHeader();
            th.setForeground(Color.black);
            th.setBackground(Color.white);
            Request.setVisible(true);
            Contacts.setVisible(false);
            Groups.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MyContactsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanelRequestMouseClicked

    private void jButtonSendGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSendGroupActionPerformed

    private void jButtonDeleteGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteGroupActionPerformed
       
    }//GEN-LAST:event_jButtonDeleteGroupActionPerformed

    private void jTableGroupsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGroupsMouseClicked
        int rowIndex = jTableGroups.getSelectedRow();
        jTextFieldGroupsName.setText(jTableGroups.getValueAt(rowIndex,1).toString());
        jTextFieldGroupsId.setText(jTableGroups.getValueAt(rowIndex,0).toString());
    }//GEN-LAST:event_jTableGroupsMouseClicked

    private void jButtonCreatGroup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreatGroup1ActionPerformed
        
    }//GEN-LAST:event_jButtonCreatGroup1ActionPerformed

    private void jButtonRequestAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRequestAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRequestAddActionPerformed

    private void jButtonRequestRefuseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRequestRefuseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRequestRefuseActionPerformed

    private void jTableRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRequestMouseClicked
       
        int rowIndex = jTableRequest.getSelectedRow();
        jTextRequestId1.setText(jTableRequest.getValueAt(rowIndex,0).toString());
        jTextRequestUserId.setText(jTableRequest.getValueAt(rowIndex,1).toString());
        jTextFieldRequestFname.setText(jTableRequest.getValueAt(rowIndex,2).toString());
        jTextFieldRequestLname.setText(jTableRequest.getValueAt(rowIndex,3).toString());
        jTextFieldRequestUname.setText(jTableRequest.getValueAt(rowIndex,4).toString());
        jTextRequestGroupID.setText(jTableRequest.getValueAt(rowIndex,5).toString());
        
    }//GEN-LAST:event_jTableRequestMouseClicked

    private void jButtonCreatGroup1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreatGroup1MouseClicked
        String gname = jTextFieldGroupsName.getText();
        if(gname.isEmpty() ){
            JOptionPane.showMessageDialog(null, "You Must Fill  Fields");
        }else{     
            try {
                group g = new group(null,gname,currentsUserId);
                groupQuery cq = new groupQuery();
                cq.insertGroup(g,currentsUserId);
                    refreshJtable();
                clearFields();
            } catch (SQLException ex) {
                Logger.getLogger(MyContactsForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonCreatGroup1MouseClicked

    private void jLabelClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClose1MouseClicked

    private void jButtonEditGroup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditGroup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditGroup1ActionPerformed

    private void jButtonEditGroup1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditGroup1MouseClicked
        if(!jTextFieldGroupsId.getText().equals("")){
            int id = Integer.valueOf(jTextFieldGroupsId.getText());
            String gname = jTextFieldGroupsName.getText();
           

            group g = new group(id,gname,currentsUserId);
            groupQuery gq = new groupQuery();
            gq.updateGroup(g);
            refreshJtable();
        }else{
            JOptionPane.showMessageDialog(null, "Select A Contact From Table");
        }
    }//GEN-LAST:event_jButtonEditGroup1MouseClicked

    private void jLabelClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClose2MouseClicked

    private void jLabelClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClose3MouseClicked

    private void jButtonDeleteGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteGroupMouseClicked
         if(!jTextFieldGroupsId.getText().equals("")){
            int id = Integer.valueOf(jTextFieldGroupsId.getText());
            groupQuery gq = new groupQuery();
            gq.deleteGroup(id);
            clearFields();
            refreshJtable();
        }else{
            JOptionPane.showMessageDialog(null, "Select A Group From Table");
        }
    }//GEN-LAST:event_jButtonDeleteGroupMouseClicked

    private void jButtonSendGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSendGroupMouseClicked
      String GroupName=jTextFieldGroupsSend.getText();
      groupQuery gq = new groupQuery();
      gq.sendRequest(GroupName,currentsUserId);
      clearFields();
      refreshJtable();
      
    }//GEN-LAST:event_jButtonSendGroupMouseClicked

    private void jButtonRequestAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRequestAddMouseClicked
        Integer id = Integer.valueOf(jTextRequestId1.getText());
        Integer userid = Integer.valueOf(jTextRequestUserId.getText());
        Integer groupid = Integer.valueOf(jTextRequestGroupID.getText());

        if(id==null ){
            JOptionPane.showMessageDialog(null, "You Must Fill All Fields");
        }else{     
        user c = new user(id,userid,null,null,null,groupid,currentsUserId);
        userQuery cq = new userQuery();
        cq.insertMember(c,currentsUserId);
        refreshJtable();
        clearFields();
        }
    }//GEN-LAST:event_jButtonRequestAddMouseClicked

    private void jButtonRequestRefuseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRequestRefuseMouseClicked
        Integer id = Integer.valueOf(jTextRequestId1.getText());
        Integer userid = Integer.valueOf(jTextRequestUserId.getText());
        if(id==null ){
            JOptionPane.showMessageDialog(null, "You Must Fill All Fields");
        }else{     
        user c = new user(id,userid,null,null,null,null,currentsUserId);
        userQuery cq = new userQuery();
        cq.DeleteRequest(id);
        refreshJtable();
        clearFields();
        }
    }//GEN-LAST:event_jButtonRequestRefuseMouseClicked

    private void jTextRequestUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRequestUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRequestUserIdActionPerformed

    private void jTextRequestGroupIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRequestGroupIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRequestGroupIDActionPerformed

    // ---------------------------------switch between colors for Active/inactive color
    
    public void setPanelColor(JPanel lbl)
    {
        lbl.setBackground( new Color(226,117,123));
    }
    
    public void resetPanelColor(JPanel lbl)
    {
        lbl.setBackground( new Color(196,91,98));
    }
    
    // --------------------------------- End -----------
    
    
    // ---------------------- Create Group --------------
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyContactsForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contacts;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Groups;
    private javax.swing.JPanel Request;
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButtonAddContact1;
    private javax.swing.JButton jButtonCreatGroup1;
    private javax.swing.JButton jButtonDeleteContact;
    private javax.swing.JButton jButtonDeleteGroup;
    private javax.swing.JButton jButtonEditContact;
    private javax.swing.JButton jButtonEditGroup1;
    private javax.swing.JButton jButtonRequestAdd;
    private javax.swing.JButton jButtonRequestRefuse;
    private javax.swing.JButton jButtonSendGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelClose1;
    private javax.swing.JLabel jLabelClose2;
    private javax.swing.JLabel jLabelClose3;
    public javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanelContacts;
    private javax.swing.JPanel jPanelGroups;
    private javax.swing.JPanel jPanelMainContacts;
    private javax.swing.JPanel jPanelMainContacts1;
    private javax.swing.JPanel jPanelMainContacts3;
    private javax.swing.JPanel jPanelRequest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableGroups;
    private javax.swing.JTable jTableRequest;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldFname1;
    private javax.swing.JTextField jTextFieldGroupsId;
    private javax.swing.JTextField jTextFieldGroupsName;
    private javax.swing.JTextField jTextFieldGroupsSend;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldRequestFname;
    private javax.swing.JTextField jTextFieldRequestLname;
    private javax.swing.JTextField jTextFieldRequestUname;
    private javax.swing.JTextField jTextRequestGroupID;
    private javax.swing.JTextField jTextRequestId1;
    private javax.swing.JTextField jTextRequestUserId;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables

    
}
